import { Schema, field, text, json } from '@nozbe/watermelondb';

export const schema = new Schema({
  name: 'agrotensor',
  version: 1,
  tables: [
    { name: 'projects', columns: [
      { name: 'title', type: 'string' },
      { name: 'start_date', type: 'string' },
      { name: 'created_at', type: 'string' },
      { name: 'updated_at', type: 'string' },
      { name: 'project_type', type: 'string' },
      { name: 'custom_columns', type: 'string', isOptional: true },
      { name: 'custom_column_types', type: 'string', isOptional: true },
      { name: 'record_type', type: 'string' },
      { name: 'is_completed', type: 'boolean' },
      { name: 'completed_at', type: 'string', isOptional: true },
      { name: 'details', type: 'string', isOptional: true },
      { name: 'deleted_at', type: 'string', isOptional: true },
      { name: 'is_deleted', type: 'boolean' },
    ]},
    { name: 'records', columns: [
      { name: 'project_id', type: 'string', isIndexed: true },
      { name: 'date', type: 'string' },
      { name: 'item', type: 'string', isOptional: true },
      { name: 'produce_amount', type: 'number' },
      { name: 'produce_revenue', type: 'number' },
      { name: 'comment', type: 'string' },
      { name: 'is_locked', type: 'boolean' },
      { name: 'locked_at', type: 'string', isOptional: true },
      { name: 'custom_fields', type: 'string', isOptional: true },
      { name: 'created_at', type: 'string' },
      { name: 'updated_at', type: 'string' },
      { name: 'is_batch_sale', type: 'boolean', isOptional: true },
      { name: 'is_carried_balance', type: 'boolean', isOptional: true },
      { name: 'source_record_ids', type: 'string', isOptional: true },
      { name: 'sold_quantity', type: 'number', isOptional: true },
      { name: 'available_quantity', type: 'number', isOptional: true },
      { name: 'batch_sale_id', type: 'string', isOptional: true },
    ]},
    { name: 'animals', columns: [
      { name: 'project_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string' },
      { name: 'sex', type: 'string' },
      { name: 'age', type: 'string', isOptional: true },
      { name: 'birth_date', type: 'string', isOptional: true },
      { name: 'breed', type: 'string', isOptional: true },
      { name: 'health_status', type: 'string' },
      { name: 'current_status', type: 'string', isOptional: true },
      { name: 'acquisition_cost', type: 'number', isOptional: true },
      { name: 'notes', type: 'string', isOptional: true },
      { name: 'mother_id', type: 'string', isOptional: true },
      { name: 'father_id', type: 'string', isOptional: true },
      { name: 'created_at', type: 'string' },
      { name: 'updated_at', type: 'string' },
      { name: 'is_locked', type: 'boolean' },
      { name: 'locked_at', type: 'string', isOptional: true },
      { name: 'mating_history', type: 'string', isOptional: true },
      { name: 'pregnancy_history', type: 'string', isOptional: true },
      { name: 'birth_records', type: 'string', isOptional: true },
      { name: 'death_records', type: 'string', isOptional: true },
      { name: 'sale_records', type: 'string', isOptional: true },
      { name: 'treatment_history', type: 'string', isOptional: true },
    ]},
  ],
});
